baseURL: "https://www.hulin.dev"
defaultContentLanguage: "en"
languages:
  zh:
    contentDir: "content/zh"
    title: "INNER PEACE"
    menu:
      main:
        - name: Github
          url: https://github.com/flyingalex
        - name: 关于
          url: /zh/about
        - name: 生活
          url: /zh/life
        - name: 技术
          url: /zh/tech
        - name: 工具
          url: /zh/tool
        - name: Archive
          url: /zh/categories
        - name: EN
          url: /en
  en:
    contentDir: "content/en"
    title: "INNER PEACE"
    menu:
      main:
        - name: Github
          url: https://github.com/flyingalex
        - name: About
          url: /about
        - name: Life
          url: /life
        - name: Tech
          url: /tech
        # - name: Tool
        # url: /en/tool
        - name: 中文
          url: /zh
theme: "framer"
algolia:
  index: "blog"
  key: "093601b4bd8cea8a8c59a9f58ed2dad4"
  appID: "DIISOO4383"
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: gruvbox
