baseURL: "https://www.hulin.ink"
defaultContentLanguage: "zh"
languages:
  zh:
    contentDir: "content/zh"
    title: "INNER PEACE"
    menu:
      main:
      - name: Github
        url: https://github.com/flyingalex
      - name: 关于
        url: /about
      - name: 生活
        url: /life
      - name: 技术
        url: /tech
      - name: 工具
        url: /tool
      - name: Archive
        url: /categories
      - name: EN
        url: /en
  en:
    contentDir: "content/en"
    title: "INNER PEACE"
    menu:
      main:
      - name: Github
        url: https://github.com/flyingalex
      - name: About
        url: /en/about
      - name: Life
        url: /en/life
      - name: Tech
        url: /en/tech
      # - name: Tool
        # url: /en/tool
      - name: 中文
        url: /
theme: "framer"
algolia:
  index: "blog"
  key: "093601b4bd8cea8a8c59a9f58ed2dad4"
  appID: "DIISOO4383"