---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "River's Site"
theme: "beautifulhugo"
metaDataFormat: "yaml"
algolia:
    index: "blog"
    key: "093601b4bd8cea8a8c59a9f58ed2dad4"
    appID: "DIISOO4383"
---